version: "2"
services:
  sandbox:
    image: semtech/ember-proxy-service
    ports:
      - "9000:80"
    links:
      - identifier:backend
    volumes:
      - ./mu-query-rewriter-sandbox:/app
  identifier:
    image: semtech/mu-identifier:1.3.0
    links:
      - dispatcher:dispatcher
    ports:
      - "8011:80"
  dispatcher:
    image: semtech/mu-dispatcher:1.1.0
    links:
      - resource:resource
      - as:as
    volumes:
      - ./config/dispatcher:/config
    ports:
      - "4028:80"
  as:
    build: ./mu-query-rewriter
    links:
      - db:database
    environment:
      MESSAGE_LOGGING: "true"
      PRINT_SPARQL_QUERIES: "true"
      CALCULATE_ANNOTATIONS: "true"
      REWRITE_SELECT_QUERIES: "true"
      PLUGIN: "elastic-prototype"
      DEBUG: "true"
      SEND_DELTAS: "true"
    volumes:
      - ./config/rewriter:/config
    ports:
      - "4005:4005"
      - "4027:8890"
  db:
    image: tenforce/virtuoso:1.0.0-virtuoso7.2.4
    environment:
      SPARQL_UPDATE: "true"
      DEFAULT_GRAPH: "http://mu.semte.ch/application"
    ports:
      - "8890:8890"
    volumes:
      - ./data/db:/data
  resource:
    image: semtech/mu-cl-resources
    environment:
      MU_DECLARE_RESOURCE_TYPES: "true"
    links:
      - as:database
    volumes:
      - ./config/resources:/config
    ports:
      - "4444:80"
  elastic:
    build: ./mu-elastic-search
    ports:
      - 8888:80
    links:
      - as:database
      - db:db
    environment:
      RACK_ENV: development
    volumes:
      - ./mu-elastic-search:/app
      - ./mu-elastic-search/config:/config
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.1
    volumes:
      - ./data/elasticsearch:/usr/share/elasticsearch/data
    ports:
      - 9200:9200    
  kibana:
    image: docker.elastic.co/kibana/kibana:6.4.2
    ports:
      - 5601:5601